### ISSUE TITLE
Help with EpiDoc and EFES exercise

### ISSUE THREAD

**Issue by gabrielbodard** [SunoikisisDC/SunoikisisDC-2020-2021#6]
If you have any difficulties with either encoding your files in EpiDoc or setting up the EFES platform to view them, please feel free to post in this thread and we (or your colleagues) may be able to help.

**Comment by chiaradimaio** [comment]
Dear Gabriel and Irene, 
I tried downloading EFES and setting it up, but I keep on getting this error message. Maybe I did not 'unpack the zip' properly: I would be glad if you could tell me exactly which procedure to follow in order to do so. Thank you in advance and sorry for the disturb.
![Screenshot (35)](https://user-images.githubusercontent.com/72555469/97107807-5f66bd80-16c1-11eb-9d1b-9881c43bb62e.png)

**Comment by nicolealexandra33** [comment]
Hi all,
Sorry but I have been trying to figure out the Java situation for the last few days-- Java doesn't work on either of my browsers, so I was hoping I could download it directly to my GitHub desktop app. Do you know if this is possible and how to do this?
Thanks!

**Comment by IreneVagionakis** [comment]
Unpacking the ZIP:
- ensure that you have downloaded the repository as a ZIP file (and not cloned it or opened it with GitHub Desktop)
- ensure that you have a ZIP extractor software/utility installed on your computer, e.g. WinZip, WinRAR, or [7-Zip](https://www.7-zip.org/)
- find where your downloaded 'EFES-master.zip' file is on your computer (possibly in Downloads?)
- right-click the file and select 'Extract' or 'Unzip' or 'Unpack' (the verb may change depending on which extractor you have installed on your computer)
- check the path of your extracted 'EFES-master' folder: sometimes the extractor may create another folder layer, e.g. EFES-master/EFES-master
- through the Command Line, enter that folder. If you are not sure of the path, you can divide the 'cd' command in smaller steps: enter the folder where your 'EFES-master' folder is (e.g. `cd Desktop` or `cd Downloads`), then use a `dir` command to see all its files and folders; then enter the 'EFES-master' folder with `cd EFES-master` (or whatever the name of the folder is), then `dir` again to check if you are already inside the right folder, until you see among the listed files and folders the build.bat file: then you can launch EFES by running the `build.bat` command

**Comment by IreneVagionakis** [comment]
Java: no, it is not something that can be installed 'inside' GitHub Desktop, but it has to be installed globally on your computer.
- check with the `java -version` command on the Command Line whether Java is already installed on your computer or not
- if not, download the Java Development Kit (JDK) from [here](https://www.oracle.com/java/technologies/javase/javase-jdk8-downloads.html):
   - first create an Oracle account
   - then download the latest JDK available that is compatible with your Operating System (currently the latest JDK is Java SE Development Kit 8u271)

Let us know if you still have problems with Java!
